version: '2'

services:
  selenium:
    image: selenium/standalone-chrome:4
    restart: unless-stopped
    mem_limit: 2g
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
  immopushr:
    image: tldevde/immopushr
    restart: unless-stopped
    volumes:
      - immopushr_db:/app/db
      - immopushr_logs:/app/logs
    environment:
      - CAPTCHA_TOKEN=ADD_YOUR_2CAPTCHA_TOKEN_HERE
      - TELEGRAM_BOT_TOKEN=ADD_YOUR_TELEGRAM_BOT_TOKEN_HERE
      - TELEGRAM_CHATS=ADD_YOUR_TELEGRAM_CHAT_IDS_HERE
      - CRON_PATTERN=50 7-22 * * *
      - SELENIUM_URL=http://selenium:4444
      - URLS=https://www.immobilienscout24.de/Suche/radius/wohnung-mieten?centerofsearchaddress=Berlin;;;;;&numberofrooms=1.5-&price=-1000.0&pricetype=rentpermonth&geocoordinates=52.51051;13.43068;4.0&sorting=2

volumes:
  immopushr_db:
  immopushr_logs: